### PR TITLE
fixed remove the suffix from the main interface date

### PR DESCRIPTION
**Pull request by ZhangChengLin**
closed https://github.com/williamtroup/Calendar.js/issues/201

### CODE REVIEW

**Review by ZhangChengLin — COMMENTED** [review]
OK

**Review by ZhangChengLin — COMMENTED** [review]
It looks good and is formatted the same as the English translation.

**Comment by ZhangChengLin** [comment]
@williamtroup

**Comment by williamtroup** [comment]
Will take a look for the next release.

**Comment by williamtroup** [comment]
Added this to v2.10.8.  Will be out in a few days.

**Pull request closed without merging**
